{"frames":[{"func":"read_rds(here(\"test\", \"table11.rds\"))","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"readRDS(con, refhook = refhook)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error in readRDS(con, refhook = refhook) : cannot open the connection\n"}